/*
"""
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""
*/

public class Euler_2 {
  public static void main (String args[]) {

    int sumNum = 2;
    int varA = 1;
    int varB = 2;
    while (varB < 4000000) {
      int varC = varA + varB;
      if (varC % 2 == 0) {
        System.out.println(varC);
        sumNum += varC;
      }
      varA = varB;
      varB = varC;
    }
    System.out.println(sumNum);
  }
}
